baseURL = "https://chierotti.it"
title = "chierotti.it"
author = "Chieroz"
copyright = "Copyright Â© 2026, Carlo Mario Chierotti."
languageCode = "it-IT"
enableRobotsTXT = true

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[permalinks]
  netiquette = "/:slug/"

[params]
  description = "Sito di Carlo Mario Chierotti, sviluppatore"
  favicon = "images/favicon.png"
  images = ["images/share.png"]
  title = "CMC Website"
